modules:
  - name: runtime
    config:
      "@type": cosmos.app.runtime.v1alpha1.Module
      app_name: MiniApp
      # NOTE: staking module is required if HistoricalEntries param > 0
      begin_blockers: [staking]
      end_blockers: [staking]
      # NOTE: The genutil module must occur after staking so that pools are properly initialized with tokens from genesis accounts.
      # NOTE: The genutil module must also occur after auth so that it can access the params from auth.
      init_genesis: [auth, bank, staking, genutil, checkers]
      override_store_keys:
        - module_name: auth
          kv_store_key: acc
  - name: auth
    config:
      "@type": cosmos.auth.module.v1.Module
      bech32_prefix: mini
      module_account_permissions:
        - account: fee_collector
        - account: bonded_tokens_pool
          permissions: [burner, staking]
        - account: not_bonded_tokens_pool
          permissions: [burner, staking]
  - name: bank
    config:
      "@type": cosmos.bank.module.v1.Module
      blocked_module_accounts_override:
        [auth, bonded_tokens_pool, not_bonded_tokens_pool]
  - name: staking
    config:
      "@type": cosmos.staking.module.v1.Module
  - name: consensus
    config:
      "@type": cosmos.consensus.module.v1.Module
  - name: genutil
    config:
      "@type": cosmos.genutil.module.v1.Module
  - name: tx
    config:
      "@type": cosmos.tx.config.v1.Config
  - name: checkers
    config:
      "@type": alice.checkers.module.v1.Module
